apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blackduck-wintermute-cohorts
  labels:
    app.kubernetes.io/name: blackduck-wintermute
    app.kubernetes.io/component: cohort-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blackduck-wintermute-source-data
  labels:
    app.kubernetes.io/name: blackduck-wintermute
    app.kubernetes.io/component: source-state
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blackduck-wintermute-jira-data
  labels:
    app.kubernetes.io/name: blackduck-wintermute
    app.kubernetes.io/component: jira-state
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blackduck-wintermute-datadog-data
  labels:
    app.kubernetes.io/name: blackduck-wintermute
    app.kubernetes.io/component: datadog-state
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blackduck-wintermute-scm-data
  labels:
    app.kubernetes.io/name: blackduck-wintermute
    app.kubernetes.io/component: scm-state
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
