apiVersion: v1
kind: ServiceAccount
metadata:
  name: blackduck-wintermute-cohort
  labels:
    app.kubernetes.io/name: blackduck-wintermute
    app.kubernetes.io/component: cohort
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: blackduck-wintermute-cohort-executor
  labels:
    app.kubernetes.io/name: blackduck-wintermute
    app.kubernetes.io/component: cohort
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtaskresults
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: blackduck-wintermute-cohort-executor
  labels:
    app.kubernetes.io/name: blackduck-wintermute
    app.kubernetes.io/component: cohort
subjects:
  - kind: ServiceAccount
    name: blackduck-wintermute-cohort
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: blackduck-wintermute-cohort-executor
