apiVersion: v1
kind: Secret
metadata:
  name: blackduck-wintermute-credentials
type: Opaque
stringData:
  BLACKDUCK_URL: REPLACE_ME
  BLACKDUCK_API_TOKEN: REPLACE_ME
  JIRA_URL: REPLACE_ME
  JIRA_USER: REPLACE_ME
  JIRA_API_TOKEN: REPLACE_ME
