apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pvc.yaml
  - cronjob.yaml

configMapGenerator:
  - name: blackduck-harness-jira-config
    files:
      - jira-rollup-config.json

generatorOptions:
  disableNameSuffixHash: true
