apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blackduck-harness-data
  labels:
    app.kubernetes.io/name: blackduck-harness
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
