apiVersion: v2
name: blackduck-wintermute-jira
description: Black Duck to Jira scheduled pipeline without Argo
type: application
version: 0.3.0
appVersion: "0.3.0"
kubeVersion: ">=1.27.0-0"
keywords:
  - blackduck
  - jira
  - security
  - cronjob
