apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: blackduck-harness

resources:
  - ../../base
  - namespace.yaml

images:
  - name: blackduck-harness
    newName: registry.invalid/customer/blackduck-harness
    newTag: replace-me

patches:
  - path: cronjob-patch.yaml

configMapGenerator:
  - name: blackduck-harness-jira-config
    behavior: replace
    files:
      - jira-rollup-config.json

generatorOptions:
  disableNameSuffixHash: true
