apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: blackduck-wintermute-local

resources:
  - ../../cohort
  - namespace.yaml

patches:
  - path: schedule-patch.yaml
  - path: insecure-network-patch.json
    target:
      group: argoproj.io
      version: v1alpha1
      kind: WorkflowTemplate
      name: blackduck-wintermute-cohort

configMapGenerator:
  - name: blackduck-wintermute-cohort-jira-config
    behavior: replace
    files:
      - jira-rollup-config.json

generatorOptions:
  disableNameSuffixHash: true
