apiVersion: v1
kind: Secret
metadata:
  name: blackduck-wintermute-blackduck-credentials
  namespace: blackduck-wintermute
type: Opaque
stringData:
  BLACKDUCK_URL: https://blackduck.example.invalid
  BLACKDUCK_API_TOKEN: ""
