apiVersion: v1
kind: Secret
metadata:
  name: blackduck-wintermute-datadog-credentials
  namespace: blackduck-wintermute
type: Opaque
stringData:
  DATADOG_API_KEY: ""
  DATADOG_SITE: datadoghq.eu
  DATADOG_INSECURE: "false"
