apiVersion: v1
kind: Secret
metadata:
  name: blackduck-wintermute-jira-credentials
  namespace: blackduck-wintermute
type: Opaque
stringData:
  JIRA_URL: REPLACE_ME
  JIRA_USER: REPLACE_ME
  JIRA_API_TOKEN: ""
