apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blackduck-wintermute-cip-data
  labels:
    app.kubernetes.io/name: blackduck-wintermute
    app.kubernetes.io/component: cip-actions
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
