"""Destination-neutral Black Duck collection services."""

from wintermute.blackduck.cache import ApiResponseCache
from wintermute.blackduck.resolver import (
    ScopeResolutionFailure,
    ScopeResolutionResult,
    resolve_collection_scope,
)
from wintermute.blackduck.candidates import (
    CandidateDiscoveryCriteria,
    build_candidate_row,
    candidate_cache_settings,
    candidate_external_id,
    candidate_key,
    count_policy_violations,
    count_vulnerable_components,
    scan_candidate,
    stable_candidate,
)
from wintermute.blackduck.client import BlackDuckClient
from wintermute.blackduck.pull import (
    PullExecution,
    PullRequest,
    pull_rows,
    pull_scope,
)
from wintermute.blackduck.projections import (
    datadog_finding_rows,
    jira_parent_rollup_rows,
)
from wintermute.blackduck.filtering import (
    broad_collection_criteria,
    filter_findings,
    finding_matches_criteria,
)
from wintermute.blackduck.cohort import (
    COHORT_SCHEMA_VERSION,
    CohortError,
    LoadedCohort,
    create_cohort_id,
    load_cohort,
    write_cohort,
)
from wintermute.blackduck.collector import (
    CollectionFailure,
    CollectionRunResult,
    TargetCollectionResult,
    collect_component_findings,
    collect_target,
    collect_targets,
    component_details,
    get_vulnerable_components,
    policy_match,
)
from wintermute.blackduck.criteria import (
    CollectionCriteria,
    ScoreOperator,
    datadog_high_risk_criteria,
    jira_parent_rollup_criteria,
)
from wintermute.blackduck.discovery import (
    LineageDiscoveryFailure,
    LineageDiscoveryResult,
    ParentScanResult,
    discover_parent_relationships,
)
from wintermute.blackduck.inventory import (
    InventoryFailure,
    InventoryFilter,
    InventoryItem,
    InventoryResult,
    build_project_version_inventory,
    get_project_versions,
    version_created,
    version_name,
    version_updated,
)
from wintermute.blackduck.lineage import (
    PROJECT_VERSION_RE,
    build_project_version_indexes,
    discover_lineage_contexts,
    extract_project_version_hrefs,
    get_bom_components,
    lineage_context_to_row,
    project_href_from_version_href,
    resolve_project_version,
)
from wintermute.blackduck.manifest import (
    CollectionManifest,
    build_collection_manifest,
    partition_targets,
    target_shard,
)
from wintermute.blackduck.models import (
    CollectionTarget,
    LineageContext,
    NormalizedFinding,
    ProjectVersionRef,
)
from wintermute.blackduck.scopes import (
    CollectionScope,
    normalize_scope,
    resolve_targets,
    targets_from_candidates,
    targets_from_parent_relationships,
)

__all__ = [
    "ApiResponseCache",
    "BlackDuckClient",
    "CollectionCriteria",
    "CollectionManifest",
    "CollectionScope",
    "CollectionTarget",
    "InventoryFailure",
    "InventoryFilter",
    "InventoryItem",
    "InventoryResult",
    "LineageContext",
    "NormalizedFinding",
    "ProjectVersionRef",
    "ScoreOperator",
    "build_collection_manifest",
    "build_project_version_inventory",
    "datadog_high_risk_criteria",
    "get_project_versions",
    "jira_parent_rollup_criteria",
    "normalize_scope",
    "partition_targets",
    "resolve_targets",
    "target_shard",
    "targets_from_candidates",
    "targets_from_parent_relationships",
    "version_created",
    "version_name",
    "version_updated",
    "PROJECT_VERSION_RE",
    "build_project_version_indexes",
    "discover_lineage_contexts",
    "extract_project_version_hrefs",
    "get_bom_components",
    "lineage_context_to_row",
    "project_href_from_version_href",
    "resolve_project_version",
    "CollectionFailure",
    "CollectionRunResult",
    "TargetCollectionResult",
    "collect_component_findings",
    "collect_target",
    "collect_targets",
    "component_details",
    "get_vulnerable_components",
    "policy_match",
    "datadog_finding_rows",
    "jira_parent_rollup_rows",
    "PullExecution",
    "PullRequest",
    "pull_rows",
    "CandidateDiscoveryCriteria",
    "ScopeResolutionFailure",
    "ScopeResolutionResult",
    "build_candidate_row",
    "candidate_cache_settings",
    "candidate_external_id",
    "candidate_key",
    "count_policy_violations",
    "count_vulnerable_components",
    "pull_scope",
    "resolve_collection_scope",
    "scan_candidate",
    "stable_candidate",
    "LineageDiscoveryFailure",
    "LineageDiscoveryResult",
    "ParentScanResult",
    "discover_parent_relationships",
    "COHORT_SCHEMA_VERSION",
    "CohortError",
    "LoadedCohort",
    "broad_collection_criteria",
    "create_cohort_id",
    "filter_findings",
    "finding_matches_criteria",
    "load_cohort",
    "write_cohort",
]
